### ISSUE TITLE
pcap_loop abnomal exit under large flow

### ISSUE THREAD

**Issue by xfliu2665** [the-tcpdump-group/libpcap#1087]
for capture pkts,  code like this:
    port init:
```
    pcap_lookupnet("eth0", &net, &mask, errbuf);
    handle = pcap_open_live("eth0", 2048, 1,1000, errbuf);
    pcap_compile(handle, &bpf_prog, "udp port 1234", 0, net);
    pcap_setfilter(handle, &bpf_prog);
```
    create recv thread and porcess func like this:
```
    PCAP_RX * prx = (PCAP_RX *)arg;
    int rc = pcap_loop(prx->handle, -1, pcap_run, (u_char *)prx);
    if (rc < 0)
    {
        fprintf(stderr, "pcap_loop error, rx:%d(%s)\n", rc, pcap_geterr(prx->handle));
    }
```
After running for a period of time, function 'pcap_loop' exit, return a large value, output like'pcap_loop error, rx:-1820639815()'. 
I run it in Centos7.3  3.10 kernel with libpcap 1.10.1.

**Comment by guyharris** [comment]
What if you do

    int rc = pcap_loop(prx->handle, 2147483647, pcap_run, (u_char *)prx);

instead?

**Comment by xfliu2665** [comment]
> What if you do
> 
> ```
> int rc = pcap_loop(prx->handle, 2147483647, pcap_run, (u_char *)prx);
> ```
> 
> instead?

I'd like capturing pkts continuously, but it's seems that, in func 'pcap_read_linux_mmap_v3': 
	```
int pkts = 0;
... ...
while ((pkts < max_packets) || PACKET_COUNT_IS_UNLIMITED(max_packets)) {
		int packets_to_read;

		if (handlep->current_packet == NULL) {
			h.raw = RING_GET_CURRENT_FRAME(handle);
			if (h.h3->hdr.bh1.block_status == TP_STATUS_KERNEL)
				break;

			handlep->current_packet = h.raw + h.h3->hdr.bh1.offset_to_first_pkt;
			handlep->packets_left = h.h3->hdr.bh1.num_pkts;
		}
... ...
return pkts;
```
code runs the 'break' breanch,  and the integer type 'pkts' is inversed and becoming negative, then return 'pkts'. 
So, I got a big values, like -1820639815 ...

**Comment by xfliu2665** [comment]
hi,all:




&nbsp; &nbsp; &nbsp;after return pkts by read_op, pcap_loop will check the return value.
pcap_loop:
	for (;;) {
		if (p-&gt;rfile != NULL) {
			/*
			 * 0 means EOF, so don't loop if we get 0.
			 */
			n = pcap_offline_read(p, cnt, callback, user);
		} else {
			/*
			 * XXX keep reading until we get something
			 * (or an error occurs)
			 */
			do {
				n = p-&gt;read_op(p, cnt, callback, user);
			} while (n == 0);
		}
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //n is negative even max_packets is -1
		if (n <= 0)
			return (n);&nbsp; &nbsp;// exit now, but i want pcap_loop to run all the time
		if (!PACKET_COUNT_IS_UNLIMITED(cnt)) {
			cnt -= n;
			if (cnt <= 0)
				return (0);
		}
	}




when h.h3-&gt;hdr.bh1.block_status == TP_STATUS_KERNEL is ture, a break will result to a return pkts, but pkts here may be a non positive value ,so pcap_loop will exit ,and i think this is a bug here&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-tcpdump-group/libpcap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-tcpdump-group/libpcap] pcap_loop abnomal exit under large flow (Issue #1087)





 
What if you do
 int rc = pcap_loop(prx-&gt;handle, 2147483647, pcap_run, (u_char *)prx);  
instead?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guyharris** [comment]
THe pcap_read routine should *only* return a negative value if an error occurred or if it's breaking out of the loop because `pcap_breakloop()` was called.  If it's returning a negative value when no error has occurred, that's a bug.

This also means that it must *never* return a value > 2^31-1, because any larger value won't fit in an `int`, and will look like a negative number.

This means that the read routines for Linux PF_PACKET sockets, at least, must just break out of the loop after processing 2^31-1 packets.  That could be true for some other platforms, but most of them have other limitations that would keep them from processing that many packets in one call to the read routine.

**Comment by xfliu2665** [comment]
&nbsp;but&nbsp;unfortunately it really heppens in some cases like this :
i use a pkt-gen tool send pkts to libpcap,&nbsp;when all the all pkts were processed by one irq which lead to softirq very high, and after 2^31 or above pkts captured by libpcap,&nbsp; then i quit the pkt-gen, pcap_loop will exit but i start it with a forever-run flag(max_packets is -1).&nbsp;
gdb shows a abnormal condition "h.h3-&gt;hdr.bh1.block_status == TP_STATUS_KERNEL" is true in&nbsp;&nbsp;read_op , and pkts&nbsp;&nbsp;&gt; 2^31-1， so pcap_loop exit


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-tcpdump-group/libpcap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月26日(星期三) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-tcpdump-group/libpcap] pcap_loop abnomal exit under large flow (Issue #1087)





 
THe pcap_read routine should only return a negative value if an error occurred or if it's breaking out of the loop because pcap_breakloop() was called.  If it's returning a negative value when no error has occurred, that's a bug.
 
This also means that it must never return a value &gt; 2^31-1, because any larger value won't fit in an int, and will look like a negative number.
 
This means that the read routines for Linux PF_PACKET sockets, at least, must just break out of the loop after processing 2^31-1 packets.  That could be true for some other platforms, but most of them have other limitations that would keep them from processing that many packets in one call to the read routine.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guyharris** [comment]
> but unfortunately it really heppens in some cases like this :

Nobody is saying  that it *doesn't* happen.

> i use a pkt-gen tool send pkts to libpcap when all the all pkts were processed by one irq which lead to softirq very high, and after 2^31 or above pkts captured by libpcap, then i quit the pkt-gen, pcap_loop will exit but i start it with a forever-run flag(max_packets is -1).
> gdb shows a abnormal condition "h.h3->hdr.bh1.block_status == TP_STATUS_KERNEL" is true in read_op ,

"read_op" is a pointer; in this case, it points to `pcap_read_linux_mmap_v3()`.

Why is "h.h3->hdr.bh1.block_status == TP_STATUS_KERNEL" an abnormal condition?  Unless your pkt-gen runs forever, at a speed that means that packets arrive as fast as the program using libpcap can process them, or faster than that process can process them, eventually `pcap_read_linux_mmap_v3()` will process all the packets that have been buffered, meaning the packet ring is empty, which means that "h.h3->hdr.bh1.block_status == TP_STATUS_KERNEL" will be true of *all* the buffers in the ring.

I.e., in `pcap_read_linux_mmap_v3()`, when it does

```
	h.raw = RING_GET_CURRENT_FRAME(handle);
	if (!packet_mmap_v3_acquire(h.h3)) {
		if (pkts == 0 && handlep->timeout == 0) {
			/* Block until we see a packet. */
			goto again;
		}
		return pkts;
	}
```

it is *NOT* abnormal if `packet_mmap_v3_acquire(h.h3)` returns 0.  It just means that there are no more packets in the ring to process - which, given that you "quit the pkt-gen", will eventually happen.

> and pkts > 2^31-1， so pcap_loop exit

...and, in that case, returns a value > 2^31-1 which *does not fit in an `int`* and *looks like a negative number, because the uppermost bit is set**.

I.e., what you're reporting is *the exact same problem I described*, so it "really happens" for the reason I described.

And, *fortunately*, that means the fix is "don't let `pkts`  overflow".

**Comment by xfliu2665** [comment]
> And, fortunately, that means the fix is "don't let pkts overflow".

that't to say it's really a bug here? cause i'm not quite sure . and now i add a check define in pcap-linux.c, every time before return pkts will call the define first

#define packet_permanent_run_check(pkts, max_packets) \
        do {if(pkts <= 0 && -1 == max_packets) {pkts = 1;} }while(0)

if pkts overflow , i will set pkts to 1 before return。and pcap_loop works well now

**Comment by guyharris** [comment]
> that't to say it's really a bug here?

Yes, it's *definitely* a bug.

(And the fix I'm working on makes the code simpler - `pcap_dispatch()` and `pcap_loop()` will, if the packet count is "unlimited" (i.e., <= 0), pass `INT_MAX` as the packet count to read_op, and the read_op routines don't have to check for "unlimited" themselves.)

**Comment by xfliu2665** [comment]
Thank you for your help, confirming this is a bug helps me a lot, I really appreciate it！
Wish U happy and smooth in the new year.

**Comment by guyharris** [comment]
> Thank you for your help, confirming this is a bug helps me a lot, I really appreciate it！

You're welcome!

> Wish U happy and smooth in the new year.

And I hope you have a happy new year, too.

**Comment by guyharris** [comment]
c60ebf10efd105d149f7c2d3eb15dec38af45001 in the main branch should fix this.  Try it and, if it works, we'll backport it to the 1.10 branch.

**Comment by xfliu2665** [comment]
i have tested my app with the main branch,it works well last more than 3h, and pcap_loop would exit less than a few mins before.
i think your fix works
thank you for your repairs again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-tcpdump-group/libpcap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 上午7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-tcpdump-group/libpcap] pcap_loop abnomal exit under large flow (Issue #1087)





 
c60ebf1 in the main branch should fix this.  Try it and, if it works, we'll backport it to the 1.10 branch.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HarriL** [comment]
Dear sirs,
I would like to inform you that the man page of libpcap defines `int pcap_loop(pcap_t *p, int cnt, pcap_handler callback, u_char *user); `  that  "A value of -1 or 0 for cnt is equivalent to infinity". 

So this seems to be originally a technical decision and not a bug.  Perhaps you should warn all programmers who may have used -1 some decades in their source code :-)

Source https://linux.die.net/man/3/pcap_loop

**pcap_loop(3)** - Linux man page defines: 

> "pcap_loop() processes packets from a live capture or ''savefile'' until cnt packets are processed, the end of the ''savefile'' is reached when reading from a ''savefile'', pcap_breakloop() is called, or an error occurs. It does not return when live read timeouts occur. A value of -1 or 0 for cnt is equivalent to infinity, so that packets are processed until another ending condition occurs."

Best regards Harri

**Comment by infrastation** [comment]
The man page ([here](https://www.tcpdump.org/manpages/pcap_loop.3pcap.html) is the most up to date version) discusses a function argument (input data), whereas in this case the issue concerned the function return value (output data). Does this resolve the confusion?

**Comment by guyharris** [comment]
> I would like to inform you that the man page of libpcap defines `int pcap_loop(pcap_t *p, int cnt, pcap_handler callback, u_char *user); ` that "A value of -1 or 0 for cnt is equivalent to infinity".
> 
> So this seems to be originally a technical decision and not a bug. 

The changes in c60ebf10efd105d149f7c2d3eb15dec38af45001 do not affect whether a value of -1 or 0 causes `pcap_loop()` to loop until an error occurs or the end of a capture file is reached; that still happens.

All it does is make sure that a single call to the internal read routine for the type of device on which the capture is being done, or for the type of capture file being read, will not process more than 2^31-1 packets.  Nowhere is it guaranteed that the internal routines will process packets forever, even in the absence of errors, and, given that the routine in question returns an `int` that's a count of packets processed on success, 0 on EOF, and a negative number giving an error on failure, it must never process more than a number of packets than fits into an `int` as a positive number, i.e. 2^31-1 on the platforms on which libpcap runs.

`pcap_dispatch()` only calls the internal read routine once.  -1 or 0 isn't equivalent to infinity in `pcap_dispatch()`:

       pcap_dispatch()  processes  packets from a live capture or ``savefile''
       until cnt packets are processed, the end of the  current  bufferful  of
       packets  is  reached  when doing a live capture, the end of the ``save-
       file'' is reached when reading from a ``savefile'', pcap_breakloop() is
       called,  or  an  error occurs.  Thus, when doing a live capture, cnt is
       the maximum number of packets to process before returning, but is not a
       minimum  number;  when  reading  a  live capture, only one bufferful of
       packets is read at a time, so fewer than cnt packets may be  processed.
       A  value  of  -1  or  0  for cnt causes all the packets received in one
       buffer to be processed when reading a live capture, and causes all  the
       packets in the file to be processed when reading a ``savefile''.

`pcap_loop()`, however, calls the internal read routine until an error or EOF indication is returned or until the count passed to it is reached.  If the count passed to it is -1 or 0, the count isn't checked, so it only stops if an error or EOF indication is returned; again, the internal routine returning a count > 2^31-1 is indistinguishable from an error, so the internal routine must not do that.  `pcap_loop()` does not return a packet count, so it does not *itself* have a problem with processing more than 2^31-1 packets.

I.e., it's a technical decision, and *it is still the case* - *nothing* has changed here in the behavior of `pcap_loop()` other than it now won't falsely return an error indication due to the internal read routine processing more than 2^31-1 packets in a single call.

> Perhaps you should warn all programmers who may have used -1 some decades in their source code :-)

There is nothing we need to warn them about other than "it used to be the case that, if you passed -1 or 0 on Linux with memory-mapped capture, a sufficiently high steady rate of incoming packets could cause `pcap_loop()` to return with an error indication even though no error occurred, but we've fixed that".

**Comment by HarriL** [comment]
Thx a lot for a through answer! This clarifies the case for me. Greate work you do with the libpcap!

**Comment by infrastation** [comment]
The conclusion here is that it was a bug, and the bugfix should be mentioned in the change log and propagated to 1.10.x to make this case fully addressed, correct?

**Comment by infrastation** [comment]
libpcap 1.10.2 has the bug fix and the change log entry, closing.
